### ISSUE TITLE
Estudar Requisitos

### ISSUE THREAD

**Issue by leonardomilv3** [ResidenciaTICBrisa/02_RotaOnibus#1]
- [x] Entender o que é um requisito
- [x] Entender o que é um requisito funcional
- [x] Entender o que é um requisito não funcional
- [x] Entender o que é um product backlog, sprint backlog
- [x] Entender as divisões do backlog: Épico, Feature, User Storie e critérios de aceitação
- [x] Entender como priorizar requisitos com o cliente

**Comment by joao-artl** [comment]
[Link](https://github.com/ResidenciaTICBrisa/02_RotaOnibus/blob/main/docs/EstruturaProjeto/backlog.md) para o Backlog.
