### ISSUE TITLE
Calcular a menor rota com OSRM

### ISSUE THREAD

**Issue by leonardomilv3** [ResidenciaTICBrisa/02_RotaOnibus#12]
- Ponto origem: UnB Gama
- Ponto destino: Conjunto Nacional

**Comment by joao-artl** [comment]
[Documentação](https://github.com/ResidenciaTICBrisa/02_RotaOnibus/blob/main/docs/Estudos/BenchmarkOSRM.md) sobre processo de calcular menor rota.
