### ISSUE TITLE
Calcular a menor rota com OpenStreetMap

### ISSUE THREAD

**Issue by leonardomilv3** [ResidenciaTICBrisa/02_RotaOnibus#14]
- Ponto origem: UnB Gama
- Ponto destino: Conjunto Nacional

**Comment by joao-artl** [comment]
[Documentação](https://github.com/ResidenciaTICBrisa/02_RotaOnibus/blob/main/docs/Estudos/OSM_Benchmark.md) sobre o benchmark.
