### ISSUE TITLE
Criar ata da reunião 25/07/23

### ISSUE THREAD

**Issue by leonardomilv3** [ResidenciaTICBrisa/02_RotaOnibus#17]
Criar ata da reunião do dia 25/07/23

https://unbbr-my.sharepoint.com/personal/211031771_aluno_unb_br/_layouts/15/stream.aspx?id=%2Fpersonal%2F211031771%5Faluno%5Funb%5Fbr%2FDocuments%2FGrava%C3%A7%C3%B5es%2FReuni%C3%A3o%20Cliente%20%2D%20Roteamento%20de%20%C3%94nibus%2D20230725%5F160535%2DGrava%C3%A7%C3%A3o%20de%20Reuni%C3%A3o%2Emp4&ga=1

**Comment by joao-artl** [comment]
[Ata](https://github.com/ResidenciaTICBrisa/02_RotaOnibus/blob/main/docs/AtaReuniao/AtaReuniao_2507.md) da reunião.
