### ISSUE TITLE
Estudar sobre o shapefile

### ISSUE THREAD

**Issue by leonardomilv3** [ResidenciaTICBrisa/02_RotaOnibus#18]
- Estudar até segunda-feira de manhã (antes do standup) o arquivo [.pynb](https://github.com/MAVI-Inova-UnB/Mavi-docs/blob/main/notebook/Paradas-Teste.ipynb) (Executar no próprio computador, etc.).
- Propor uma solução para o problema atual (Como integrar as paradas com as linhas de ônibus).

[DFnoPonto](https://geoserver.semob.df.gov.br/geoserver/web/wicket/bookmarkable/org.geoserver.web.demo.MapPreviewPage?0&filter=false)

**Comment by joao-artl** [comment]
[Documentação](https://github.com/ResidenciaTICBrisa/02_RotaOnibus/blob/main/docs/Estudos/EstudoShapeFiles.md) sobre o estudo do shapefile
