### ISSUE TITLE
Estudar o CSV gerado pelo Semob das paradas

### ISSUE THREAD

**Issue by leonardomilv3** [ResidenciaTICBrisa/02_RotaOnibus#19]
FAZER APENAS COM 1 TUPLA PARA TESTAGEM.

Link da planilha no telegram ou [site](https://geoserver.semob.df.gov.br/geoserver/web/wicket/bookmarkable/org.geoserver.web.demo.MapPreviewPage?0&filter=false)

- Entender o que é o point (geo_ponto_rede_pto) e transformar em coordenadas, [documentação](https://docs.geoserver.org/).

Plus:
Tratamento:
- Retirar tuplas com situacao "DESATIVADA".
- Transformar em um json com os dados:
  [
   "id": parada,
   "nome": descricao,
   "cordenadas": [longetude, latitude]
  ]

**Comment by joao-artl** [comment]
[Documentação](https://github.com/ResidenciaTICBrisa/02_RotaOnibus/blob/main/docs/Estudos/Paradas.md) sobre o CSV.
