### ISSUE TITLE
Estudar o CSV gerado pelo Semob das rotas

### ISSUE THREAD

**Issue by leonardomilv3** [ResidenciaTICBrisa/02_RotaOnibus#20]
FAZER APENAS COM 1 TUPLA PARA TESTAGEM.

Baixe os arquivos das rotas em: [site](https://geoserver.semob.df.gov.br/geoserver/web/wicket/bookmarkable/org.geoserver.web.demo.MapPreviewPage?0&filter=false)

[documentacao](https://docs.geoserver.org/)

Tarefas:
- Descobrir como transformar o linestring em algo útil para a plotagem no Folium

Plus:
- Retirar o que tiver como "DESATIVADA"
- Transformar em JSON com os dados:

[{
 "id": parada
 "nome": descricao
 "rotas": [linestring já tratado]
}]

**Comment by joao-artl** [comment]
[Documentação](https://github.com/ResidenciaTICBrisa/02_RotaOnibus/blob/main/docs/Estudos/Paradas.md) sobre o CSV.
