### ISSUE TITLE
Criar Linestring de todas as linhas do DF

### ISSUE THREAD

**Issue by leonardomilv3** [ResidenciaTICBrisa/02_RotaOnibus#22]
- [x] Nova Linestring de uma linha de onibus deve conter apenas o GPS (lat. e long.) de todas as paradas de onibus (POINT)
- [x]  As paradas de ônibus da nova Linestring devem estar ordenadas, baseadas na ordem da rota do onibus 
- [x] Armazenar novas Linestrings em um arquivo CSV 

Opcional
- [ ] Tentar aplicar o pseudoalgortimo apresentado pela Natália.

Tarefas
- [x] Tentar aplicar o pseudoalgoritmo apresentado pelo João. (Lucas, Leonardo).
- [x] Acrescentar no CSV o nome da parada e a descrição. (Natália).
- [x] Aproximar de forma que não ache duas paradas e que consiga fazer o mapeamento linestring/point (Luiz, João).

![](https://i.imgur.com/9zyrOwh.png)

**Comment by joao-artl** [comment]
[Link](https://github.com/ResidenciaTICBrisa/02_RotaOnibus/blob/main/docs/Notebooks/Estudos/LinhaOnibus-Grafo.ipynb) para algoritmo.
