### ISSUE TITLE
Criar Grafo Direcional de todas as linhas de onibus do DF

### ISSUE THREAD

**Issue by leonardomilv3** [ResidenciaTICBrisa/02_RotaOnibus#23]
- Transformar as paradas em nós do Grafo
- Adicionar as arestas do Grafo.
- Armezenar Grafo em Shapefile ou CSV

Estrutura Nó:
- Id
- GPS (lat. e long.)

Estrutura Aresta:
- número da linha de ônibus 
- distancia em metros (de uma parada até a outra)

**Comment by joao-artl** [comment]
[Algoritmo](https://github.com/ResidenciaTICBrisa/02_RotaOnibus/blob/main/docs/Notebooks/Estudos/LinhaOnibus-Grafo.ipynb) dos grafos direcionais.
