### ISSUE TITLE
Estudar sobre o Django e Django Rest Framework

### ISSUE THREAD

**Issue by leonardomilv3** [ResidenciaTICBrisa/02_RotaOnibus#4]

**Comment by joao-artl** [comment]
Links para documentação sobre [Django](https://github.com/ResidenciaTICBrisa/02_RotaOnibus/blob/main/docs/Estudos/Django.md) e [Django Rest Framework](https://github.com/ResidenciaTICBrisa/02_RotaOnibus/blob/main/docs/Estudos/DRF.md).
