### ISSUE TITLE
[API] Configuração inicial da API

### ISSUE THREAD

**Issue by leonardomilv3** [ResidenciaTICBrisa/02_RotaOnibus#40]
# Configuração da API

## Descrição
Deixar o mvp da API pronto

# Tarefas

- [x] Receber as coordenadas de origem e destino
- [x] Validar se as coordenadas são válidas
- [x] Documentação básica com o swagger
- [x] Documentar no git pages

# Critérios de aceitação

- [x] Validação funcional das coordenadas
- [x] Aceitação de 4 coordenadas
- [x] Documentação explicativa

**Comment by joao-artl** [comment]
[Documentação](https://github.com/ResidenciaTICBrisa/02_RotaOnibus/blob/main/docs/Estudos/DocumentacaoAPI.md) da API.

**Comment by joao-artl** [comment]
[Documento](https://github.com/ResidenciaTICBrisa/02_RotaOnibus/blob/main/docs/Estudos/ArquiteturaAPI.md) sobre Arquitetura da API.
