### ISSUE TITLE
[API] Testar API no DF 

### ISSUE THREAD

**Issue by leonardomilv3** [ResidenciaTICBrisa/02_RotaOnibus#43]
# Testar API no DF 

## Descrição
Testar API no DF 

# Tarefas

- [ ] Tarefa 1
- [ ] Tarefa 2
- [ ] Tarefa 3

# Critérios de aceitação

- [ ] Critério 1
- [ ] Critério 2
- [ ] Critério 3

**Comment by joao-artl** [comment]
Outra issue foi criada para executar os testes, [link](https://github.com/ResidenciaTICBrisa/02_RotaOnibus/issues/47) para outra issue.
