### ISSUE TITLE
Pesquisar algoritmo diminuir ruído paradas

### ISSUE THREAD

**Issue by leonardomilv3** [ResidenciaTICBrisa/02_RotaOnibus#44]
# Pesquisar algoritmo diminuir ruído paradas

## Descrição
Pesquisar algoritmo para diminuir ruído (paradas que não são da Linha de ônibus) das paradas encontradas na Linestring

# Tarefas

- [x] Conversar com professores para verificar se algoritmo é valido

# Critérios de aceitação

- [x] Gerar um planejamento para aplicar algoritmo

**Comment by joao-artl** [comment]
[Documentação](https://github.com/ResidenciaTICBrisa/02_RotaOnibus/blob/main/docs/Estudos/Remo%C3%A7%C3%A3oRuidos.md) da pesquisa.
