### ISSUE TITLE
Preparação dos dados e definição de limiares

### ISSUE THREAD

**Issue by luizros** [ResidenciaTICBrisa/02_RotaOnibus#45]
# Preparação dos dados e definição de limiares

## Descrição

Implementar um algoritmo que calcula a distância entre todas as paradas de uma rota de ônibus. Calcular um limiar para as distâncias entre as paradas e aplicar um filtro no dataframe das rotas com paradas.

# Tarefas

- [x] Calcular a distância entre paradas consecutivas.
- [x] Buscar um indicador a partir dos valores das distâncias encontradas, pode ser media, mediana e etc...
- [x] Usando o indicador, defina um limiar para ser usado.
- [ ] Etiquetar paradas de ida e de volta.
- [ ] Processar limiar no dataframe das paradas e remover ruidos.

# Critérios de aceitação
- [x] O limiar definido deve ser menor do a maioria das distâncias.
- [x] Armazenar as distâncias em um array(ou lista).
- [ ] O dataframe das paradas deve manter as paradas indexadas em ordem de rota.
- [x] Documentar a issue e colocar no pages

**Comment by joao-artl** [comment]
[Link1](https://github.com/ResidenciaTICBrisa/02_RotaOnibus/blob/main/docs/Notebooks/Estudos/joao.ipynb) e [Link2](https://github.com/ResidenciaTICBrisa/02_RotaOnibus/blob/main/docs/Notebooks/Estudos/LeituraParadasTratadas.ipynb) levam ao processo de definição dos limiares

**Comment by joao-artl** [comment]
Foi decidido utilizar o DBSCAN no lugar do limiar com média e mediana.
