### ISSUE TITLE
Aplicar DBSCAN no dataframe antigo

### ISSUE THREAD

**Issue by luizros** [ResidenciaTICBrisa/02_RotaOnibus#46]
# Aplicação de DBSCAN nos dataframes antigos

## Aplicar o algoritmo DBSCAN no dataframe com paradas ruidosas

# Tarefas

- [x] Aplicar DBSCAN
- [x] Documentar sobre o DBSCAN e o algoritmo utilizado

# Critérios de aceitação

- [x] Remover paradas muito próximas uma das outras
- [x] Manter o dataframe em ordem

**Comment by joao-artl** [comment]
[Algoritmo](https://github.com/ResidenciaTICBrisa/02_RotaOnibus/blob/main/docs/Notebooks/Estudos/luiz.ipynb) contendo DBSCAN.

**Comment by joao-artl** [comment]
[Documentação](https://github.com/ResidenciaTICBrisa/02_RotaOnibus/blob/main/docs/Estudos/Remo%C3%A7%C3%A3oRuidos.md) sobre o DBSCAN.
